# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('offeree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeree', to='profiles.Profile')),
                ('offeror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeror', to='profiles.Profile')),
            ],
        ),
    ]
